export { default as RButton } from './RButton.vue'
export { default as RCard } from './RCard.vue'
export { default as RCarousel } from './RCarousel.vue'
export { default as RIcon } from './RIcon.vue'
export { default as RSection } from './RSection.vue'
export { default as RStat } from './RStat.vue'
export { default as RTestimonialCard } from './RTestimonialCard.vue'
export type * from './types'
